In [1]:
import numpy as np
import pandas as pd
import random
import ast
from tqdm import tqdm
from IPython import display as ipd

# visualization
import matplotlib.pyplot as plt
from tabulate import tabulate
import seaborn as sns
#system files
import os
import json
import re
import glob

import zipfile
import shutil
import gc
from joblib import Parallel, delayed

from datasets import load_metric
#normalization
from pandarallel import pandarallel
from bnunicodenormalizer import Normalizer 
pandarallel.initialize(progress_bar=True,nb_workers=8)
tqdm.pandas()
bnorm=Normalizer()

# Set environment variables
import warnings
warnings.filterwarnings('ignore')

INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [ ]:
df=pd.read_csv('validation_with_punctuation.csv')

In [ ]:
df

In [ ]:
wer = load_metric("wer")

In [ ]:
wer_score_punctuation = wer.compute(predictions=df.punctuation, references=df.actual)
wer_score_punctuation

In [ ]:
wer_score_no_punctuation = wer.compute(predictions=df.predicted, references=df.actual)
wer_score_no_punctuation

In [ ]:
wer_score_predicts = wer.compute(predictions=df.punctuation, references=df.predicted)
wer_score_predicts

In [106]:
df_submission=pd.read_csv('submission_with_punctuation.csv')

In [107]:
df_submission

,path,sentence,punctuation
0,common_voice_bn_31584094.mp3,দ্বিতীয়ত এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী,"দ্বিতীয়ত, এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী।"
1,common_voice_bn_31617509.mp3,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে।
2,common_voice_bn_31529519.mp3,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ। দক্ষিণে রয়েছে জাভা দ্বীপ।
3,common_voice_bn_31694167.mp3,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন।
4,common_voice_bn_30999394.mp3,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই।
...,...,...,...
7742,common_voice_bn_31574515.mp3,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত।
7743,common_voice_bn_31511061.mp3,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে।
7744,common_voice_bn_31561913.mp3,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল।
7745,common_voice_bn_31524603.mp3,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন।
7746,common_voice_bn_31711361.mp3,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়।

In [108]:
wer_score_predicts = wer.compute(predictions=df_submission.prediction_no_punctuation, references=df_submission.prediction_with_punctuation)
wer_score_predicts

NameError: name 'wer' is not defined

In [109]:
df=pd.read_csv('submission_with_punctuation.csv')

In [110]:
df['punctuation']=df['punctuation'].str[:-1]

In [113]:
df['punctuation'][1575]

'যেতে না এবং অন্যান্য সর অন্তর্ভুক্ত ছিল এবং যৌন সম্পর্কিত পণ্য বিক্রয় করা হয়েছিল'

In [112]:
df['punctuation'] = df['punctuation'].str.replace('।', '')

In [114]:
df['punctuation'] = df['punctuation'].str.replace('.', '')

In [115]:
df

,path,sentence,punctuation
0,common_voice_bn_31584094.mp3,দ্বিতীয়ত এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী,"দ্বিতীয়ত, এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী"
1,common_voice_bn_31617509.mp3,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে
2,common_voice_bn_31529519.mp3,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ
3,common_voice_bn_31694167.mp3,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন
4,common_voice_bn_30999394.mp3,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই
...,...,...,...
7742,common_voice_bn_31574515.mp3,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত
7743,common_voice_bn_31511061.mp3,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে
7744,common_voice_bn_31561913.mp3,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল
7745,common_voice_bn_31524603.mp3,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন
7746,common_voice_bn_31711361.mp3,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়

In [116]:
df=df.drop('sentence',axis=1)
df['sentence'] = df['punctuation']
df=df.drop('punctuation',axis=1)

In [117]:
pd.set_option('display.max_colwidth', None)

In [130]:
comma_id=df.index[df['sentence'].str[-1] == ',']

In [136]:
nan_id=df.loc[pd.isna(df["sentence"]), :].index

In [141]:
deleted = df[df.index.isin(nan_id)]['path'].tolist()

In [142]:
df=df.drop(nan_id)
df=df.reset_index(drop=True)

In [143]:
df

,path,sentence
0,common_voice_bn_31584094.mp3,"দ্বিতীয়ত, এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী"
1,common_voice_bn_31617509.mp3,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে
2,common_voice_bn_31529519.mp3,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ
3,common_voice_bn_31694167.mp3,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন
4,common_voice_bn_30999394.mp3,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই
...,...,...
7739,common_voice_bn_31574515.mp3,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত
7740,common_voice_bn_31511061.mp3,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে
7741,common_voice_bn_31561913.mp3,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল
7742,common_voice_bn_31524603.mp3,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন
7743,common_voice_bn_31711361.mp3,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়

In [147]:
for i in range(len(df)):
    if df['sentence'][i][-1]==',':
        df['sentence'][i] = df['sentence'][i][:-1]
        print(df['sentence'][i])

যখন পত্রিকাটি তার সব কিছু বন্ধ করে দিয়ে সমস্ত কার্যক্রম ইন্টারনেট স্টাআ্ধরিত করেছিল
হেফাজতে নেওয়ার পর মেয়ে অপরাধের কথা স্বীকার করে পুলিশের কাছে বলেছে, আমি দক্ষিতআমিদক্িত
ইসলামী আইনে বিশেষ করে বলা হয়েছে প্রথুজবাই মাংস তৈরি এবং খাওয়ার রীতিনীতি সম্পর্কে বলা হয়েছে
খাদ্যশস্য জাতীয় ধান, গম, আলু, সরিষা
যদিও তিনি কাজ ক্ষমা চালিয়ে যেতে পারতেন
তিনি ছিলেন শান্তিরক্ষা মিশনে অংশগ্রহণকারী প্রথম বাংলাদেশী অফিসার, যিনি বিদেশে মিশন যারা মারা যান
যার প্রতিষ্ঠার মূল্নয়ক ছিলেন মহরুম মুহাম্মদ কাসেম নানুতাবি
এসব গানের মূল উপাদান রহস্যবাদ
পৈত্রিক নিবাস, শিলিগুড়ি
আর মেয়েদের জন্য সাদা পায়জামা, সাদা উন্নয়ন নেভি ল্বু রঙের বোরখা
এর মধ্যে রয়েছে মধ্যে পাচ্ছে দক্ষিণ পর্ব সিরিয়ার কিছু অংশ, সহততরপূর্জর্দান, উত্তর সৌদি আরব, উপশ্চিম ইরাক
পাঁচ প্রকার প্রাণ সম্মিলিতভাবে পাঁচটি বায়ু নামে পরিচিতহিন্দু ধর্মগ্রন্থে বর্ণিত হয়েছে
অমূল্য সব কাজের স্বীকৃতি হিসেবে দেশে বিদেশে পেয়েছেন অনন্য সব সম্মান, স্বীকৃতি, সংবর্ধনা, পদক
সেরা পরিচালক হিসেবে অস্কার পেয়েছিলেন যে গ্রেজিয়েট সিনেমার জন্য
প্রধান ফলফলাদি আম, কাঁঠাল, লিচু, কলা
যিনি মাত্র কয়েকটি আত্মজীবনীমূলক বই লিখে খ্যাতি অর্জন করেছেন
তাকে এই বলে উদ্ধৃত করা হয়েছে, সে কেবল এতে স্বাচ্ছন্দ্য বোধ করে
বিভিন্ন গানে কণ্ঠ দিয়েছেন সৈয়দ আদ্বুল হাদী, সাবিনা ইয়াসমিন, আদ্বুল আলীম, রুনা লায়লা
যা ভারতের আন্তর্জাতিক সীমান্তের নিকট অবস্থিত কয়েকটি অঞ্চলে চলাচল নিয়ন্ত্রণের জন্য সরকারি প্রচেষ্টার অংশ
যার সঙ্গে আছে রাইফেল
এর সমাপ্তিপিনটি হাঁটু বা উরুর উপর ভর দেওয়া থাকে যখন কোনো বাদক চেয়ারে বসে এটি বাজায়
ফেলো, আমেরিকান ফিজিক্যাল সোসাইটি
নিয়মিত লিখতেন কবিতার গান
এই উপন্যাসটিতে হুমায়ুন যা তীব্র রূপ ক্রিণাত্মকভাবে বাংলাদেশের একটি কাল্পনিক মৌলবাদী সংগঠনের চিত্র তুলে ধরেছিলেন
যিনি আলকায়েদার প্রতিষ্ঠাতা আমির ছিলেন
ফুল হলুদ কমলা
আবার কবিতাটি সামনে থেকে পল্লী রাম ও রামায়ণের কাহিনী আর কৃষ্ণ থেকে যে কৃষ্ণ ও মহমরতের কাহিনী
প্রধান কৃষি ফসল ধান, পাট, গম, আলু, সরিষা, শাকসবজি
যেহেতু সেটি অনুমোদনের জন্য খুব খখ্যাত একজন অপরাধী ছিলেন
রাজ্যটির প্রাচীন ইতিহাস অস্পষ্ট
পশ্রিত যেসব মুদ্রা, তার সাথে রয়েছে একটি করে নম্বর
ফতোয়া ও ইসলামী গবেষণা বিভাগ
বিভিন্ন আন্তর্জাতিক সংস্থার সদর দফতর এখানে অবস্থিত, যাদের মধ্যে বিশ্ব পোস্টাল ইউনিয়নের নাম উল্লেখযোগ্য
এমনকি এটি কোর্ডের জন্য বিপদজনক চেয়ে কোন কোডের ব্যাপারে সতর্ক ছিল এবং যেকোনো প্রকার বিপজ্জনক কর সহজেই মুছে ফেলতে পারতো
যাদেরকে বিজ্ঞানীরা অবাঞ্ছিত এবং স্ট্রিং তত্ত্বের ত্রুটি হিসাবে বিবেচনা করেছিলেন
প্রধান কৃষি ফসল ধান, গম, আলু, পাট, কলা, ন সরিষা ডাল
যেন ছোট পাথরের দুনিয়ার মানুষ বড়পাপের, আর বড় পাথরের দুনিয়ার মানুষ ছোটপাপের
এ জাতের গাছ মজবুত
এর সদর দপ্তর রাজধানী ঢাকায়
এদের প্রাথমিক খাদ্য ই দুর, জাতীয় ক্ষুদ্র তিখ্নুদন্ত প্রাণী
কিন্তু সৃষ্টিকর্তা চাইলে মানব ইতিহাসের পথ বদলাতে পারেনযেটি তার কাছে ভাল মনে হবে
এ দুই সপ্তাহ পর সিডনির আরেকটি স্থানে গ্লোরিয়া জিন্স তাদের যখন স্থাপন করে
মার্চ মাসে তার কোম্পানি ছিল পলাশ বাড়িতে
তার এক মেয়ে, তিন ছেলে
এটা না জাগরণ স্বপ্ন, না গভীর ঘুম
এটি বিশ্বের যে জন্য স্থানের বৃহত্তম এবং সর্বোত্তম সজ্জিত ইসলামিক সেমিনারি হিসেবে বিবেচিত হয়েছিল
আরো বলা আছে, রাষ্ট্রপতি যৌথ সশস্ত্র বাহিনীর নিয়ন্ত্রণ করবে প্রতিরক্ষা আইন অনুযায়ী
যিনি ছিলেন তৃতীয় কিং জর্জ এবং রাণী ভিক্টোরিয়ার চতুর্থ পুত্র
যার তালিকা নিম্নরূপ

In [150]:
for i in range(len(df)):
    if df['sentence'][i][-1] not in [',','?']:
        df['sentence'][i] = df['sentence'][i] + '।'

In [151]:
df

,path,sentence
0,common_voice_bn_31584094.mp3,"দ্বিতীয়ত, এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী।"
1,common_voice_bn_31617509.mp3,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে।
2,common_voice_bn_31529519.mp3,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ।
3,common_voice_bn_31694167.mp3,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন।
4,common_voice_bn_30999394.mp3,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই।
...,...,...
7739,common_voice_bn_31574515.mp3,পিতার দিক থেকে তিনি পোলীয় ও রুশ এবং মায়ের দিক থেকে তিনি হাঙ্গেরি ও পোলীয় বংশোদ্ভূত।
7740,common_voice_bn_31511061.mp3,এই শহরের নাম বৌদ্ধ ধর্মগুরু পদসম্বরের নাম থেকে হয়েছে।
7741,common_voice_bn_31561913.mp3,দুই পক্ষেই রাক্ষস নায়কদের বিশেষ ভূমিকা ছিল।
7742,common_voice_bn_31524603.mp3,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন।
7743,common_voice_bn_31711361.mp3,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়।

In [158]:
for i in range(len(deleted)):
    df = df.append({'path': deleted[i],'sentence':'',},ignore_index=True)

In [166]:
df['sentence'][7746] = 'ওয়া অনা আলা আহতিকা'

In [170]:
df

,path,sentence
0,common_voice_bn_31584094.mp3,"দ্বিতীয়ত, এটি বহুল প্রচলিত একটি রিজার্ভ কারেন্সী।"
1,common_voice_bn_31617509.mp3,জ্ঞান চর্চার সুবিধার্থে পাঠাগার আইসিটি চর্চার জন্য একটি কম্পিউটার ল্যাব রয়েছে।
2,common_voice_bn_31529519.mp3,এর উত্তর দিকে রয়েছে বরণীয় দ্বীপ দক্ষিণে রয়েছে জাভা দ্বীপ।
3,common_voice_bn_31694167.mp3,পরের বছর তিনজন কৃষ্ণাঙ্গ ব্যক্তি আইনসভায় নির্বাচিত হন।
4,common_voice_bn_30999394.mp3,কলেজটির নিজস্ব ক্যাম্পাস ভবন নেই।
...,...,...
7742,common_voice_bn_31524603.mp3,তিনি আইনজীবী হিসেবে কর্মজীবন শুরু করেন।
7743,common_voice_bn_31711361.mp3,এতে বিদ্রোহের কথা খোলা খুলি ভাবে প্রচার করা হয়।
7744,common_voice_bn_31712622.mp3,
7745,common_voice_bn_31804077.mp3,
7746,common_voice_bn_31589655.mp3,ওয়া অনা আলা আহতিকা

In [171]:
df.to_csv('lessgo1.csv',index=False)